### ISSUE TITLE
Generating a new Encounter when they are no suitable enemies to pick from crashes the app

### ISSUE THREAD

**Issue by GrafiMarfi** [DanDuhon/DSBG-Shuffle#11]
[log.txt](https://github.com/DanDuhon/DSBG-Shuffle/files/13441698/log.txt)

Tried to create Sunless City Encounter, but when no expansion is active with suitable replacement enemies, the app crashes.

**Comment by DanDuhon** [comment]
Found the issue.  When you shuffle the enemies, it checks to see if the new enemies picked are the same as the old one.  If they are, it picks again (that way it doesn't feel like the app did nothing).  It was looking at the wrong thing so it was stuck in an endless loop trying to pick a new set of enemies when there was only one.  I don't know how that got messed with, but it did.  New release 1.2.1 out shortly.  Thanks!
