### ISSUE TITLE
Feature request: printing the shuffled cards

### ISSUE THREAD

**Issue by GrafiMarfi** [DanDuhon/DSBG-Shuffle#12]
a easy way to get the cards as printable pdf (or something similar) would be nice. Especially for campaigns, when creating a lot of different encounters.

**Comment by DanDuhon** [comment]
Just the faces? Double sided printing? Options for both?

I'll probably make it part of the campaign stuff. I have some ideas for how to arrange cards efficiently per page. Need to figure out how to work with PDFs.

**Comment by DanDuhon** [comment]
Encounters can be exported to PDF after being added to a campaign.  Groups the following together for ease of arranging on pages:
- V1 levels 1-3
- V1 level 4
- V2

I used an area that should be compatible with the common page sizes.  It should at minimum fit on US Letter and A4 just fine.
